[package]
name = "withdrawal"
type = "bin"
authors = ["Voidgun Contributors"]
compiler_version = ">=0.36.0"

[dependencies]
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.1" }
