[package]
name = "transfer"
type = "bin"
authors = ["Voidgun Contributors"]
compiler_version = "=1.0.0-beta.16"

[dependencies]
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.1" }
