cm_change = ""
cm_out = ""
gas_fee_cap = ""
gas_tip = ""
merkle_index = ""
merkle_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nf_note = ""
nf_tx = ""
nk = ""
note_change_r = ""
note_change_rk_hash = ""
note_change_value = ""
note_in_r = ""
note_in_rk_hash = ""
note_in_token = ""
note_in_value = ""
note_out_r = ""
note_out_rk_hash = ""
note_out_value = ""
pool_id = ""
pub_key_x = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
pub_key_y = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
recipient_pk_x = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
recipient_pk_y = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
root = ""
signature = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
token_type = ""
tx_chain_id = ""
tx_hash = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
tx_max_fee = ""
tx_max_priority_fee = ""
tx_nonce = ""
tx_to = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
tx_value = ""
