[package]
name = "voidgun_circuits"
type = "lib"
authors = ["Voidgun Contributors"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon2 = { git = "https://github.com/TaceoLabs/noir-poseidon", tag = "v0.4.0", directory = "poseidon2" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.1" }
